image:
  file: .gitpod.Dockerfile

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - pivotal.vscode-spring-boot
    - vscode-icons-team.vscode-icons
    - coenraads.bracket-pair-colorizer
    - vscodevim.vim
    - wakatime.vscode-wakatime
